// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: term_service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTermRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term        string `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Translation string `protobuf:"bytes,2,opt,name=translation,proto3" json:"translation,omitempty"`
}

func (x *AddTermRequest) Reset() {
	*x = AddTermRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_term_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTermRequest) ProtoMessage() {}

func (x *AddTermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_term_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTermRequest.ProtoReflect.Descriptor instead.
func (*AddTermRequest) Descriptor() ([]byte, []int) {
	return file_term_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddTermRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *AddTermRequest) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

type AddTermResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTermResponse) Reset() {
	*x = AddTermResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_term_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTermResponse) ProtoMessage() {}

func (x *AddTermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_term_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTermResponse.ProtoReflect.Descriptor instead.
func (*AddTermResponse) Descriptor() ([]byte, []int) {
	return file_term_service_proto_rawDescGZIP(), []int{1}
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_term_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_term_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_term_service_proto_rawDescGZIP(), []int{2}
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Terms []*GetCollectionResponse_TermInfo `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_term_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_term_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_term_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCollectionResponse) GetTerms() []*GetCollectionResponse_TermInfo {
	if x != nil {
		return x.Terms
	}
	return nil
}

type GetCollectionResponse_TermInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term        string `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Translation string `protobuf:"bytes,2,opt,name=translation,proto3" json:"translation,omitempty"`
}

func (x *GetCollectionResponse_TermInfo) Reset() {
	*x = GetCollectionResponse_TermInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_term_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectionResponse_TermInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse_TermInfo) ProtoMessage() {}

func (x *GetCollectionResponse_TermInfo) ProtoReflect() protoreflect.Message {
	mi := &file_term_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse_TermInfo.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse_TermInfo) Descriptor() ([]byte, []int) {
	return file_term_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetCollectionResponse_TermInfo) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *GetCollectionResponse_TermInfo) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

var File_term_service_proto protoreflect.FileDescriptor

var file_term_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x72, 0x6f, 0x6d, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x65,
	0x72, 0x6d, 0x69, 0x74, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x46, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x64, 0x72, 0x6f, 0x6d, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x74, 0x65, 0x72, 0x6d, 0x73, 0x1a, 0x40, 0x0a, 0x08, 0x54, 0x65, 0x72, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xe4, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x72, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x65,
	0x72, 0x6d, 0x12, 0x1e, 0x2e, 0x64, 0x72, 0x6f, 0x6d, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x65, 0x72,
	0x6d, 0x69, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x72, 0x6f, 0x6d, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x65, 0x72,
	0x6d, 0x69, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x22, 0x08, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x65, 0x72, 0x6d, 0x3a, 0x01, 0x2a, 0x12, 0x74, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x64, 0x72, 0x6f, 0x6d,
	0x70, 0x69, 0x78, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x64, 0x72, 0x6f, 0x6d, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_term_service_proto_rawDescOnce sync.Once
	file_term_service_proto_rawDescData = file_term_service_proto_rawDesc
)

func file_term_service_proto_rawDescGZIP() []byte {
	file_term_service_proto_rawDescOnce.Do(func() {
		file_term_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_term_service_proto_rawDescData)
	})
	return file_term_service_proto_rawDescData
}

var file_term_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_term_service_proto_goTypes = []interface{}{
	(*AddTermRequest)(nil),                 // 0: drompix.termit.AddTermRequest
	(*AddTermResponse)(nil),                // 1: drompix.termit.AddTermResponse
	(*GetCollectionRequest)(nil),           // 2: drompix.termit.GetCollectionRequest
	(*GetCollectionResponse)(nil),          // 3: drompix.termit.GetCollectionResponse
	(*GetCollectionResponse_TermInfo)(nil), // 4: drompix.termit.GetCollectionResponse.TermInfo
}
var file_term_service_proto_depIdxs = []int32{
	4, // 0: drompix.termit.GetCollectionResponse.terms:type_name -> drompix.termit.GetCollectionResponse.TermInfo
	0, // 1: drompix.termit.TermService.AddTerm:input_type -> drompix.termit.AddTermRequest
	2, // 2: drompix.termit.TermService.GetCollection:input_type -> drompix.termit.GetCollectionRequest
	1, // 3: drompix.termit.TermService.AddTerm:output_type -> drompix.termit.AddTermResponse
	3, // 4: drompix.termit.TermService.GetCollection:output_type -> drompix.termit.GetCollectionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_term_service_proto_init() }
func file_term_service_proto_init() {
	if File_term_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_term_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTermRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_term_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTermResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_term_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_term_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_term_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollectionResponse_TermInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_term_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_term_service_proto_goTypes,
		DependencyIndexes: file_term_service_proto_depIdxs,
		MessageInfos:      file_term_service_proto_msgTypes,
	}.Build()
	File_term_service_proto = out.File
	file_term_service_proto_rawDesc = nil
	file_term_service_proto_goTypes = nil
	file_term_service_proto_depIdxs = nil
}
